- name: App setup 
  ansible.builtin.import_role:
    name: common
    task_from: app-setup

- name: java setup 
  ansible.builtin.import_role:
    name: common
    task_from: java-setup.yaml

- name: Mysql setup 
  ansible.builtin.import_role:
    name: common
    task_from: mysql-setup.yaml

- name: system restart setup 
  ansible.builtin.import_role:
    name: common
    task_from: systemd-setup

