[web]
web.arundev.store
[mongodb]
mongodb.arundev.store
[catalogue]
catalogue.arundev.store
[redis]
redis.arundev.store
[user]
user.arundev.store
[cart]
cart.arundev.store
[mysql]
mysql.arundev.store
[shipping]
shipping.arundev.store
[rabbitmq]
rabbitmq.arundev.store
[payment]
payment.arundev.store
[dispatch]
dispatch.arundev.store


[all:vars]
ansible_password=DevOps321