- name: Configure yum erlang repo 
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure yum rabbitmq repo 
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Enable and start
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: creating roboshop user
  ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

- name: set_permissions for roboshop user
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"